### ISSUE TITLE
Ref Arch Documentation Review: Transfer BC Content

### ISSUE THREAD

**Issue by mwmentor** [mojaloop/reference-architecture-doc#62]
### Errors and Omissions

The following errors and omissions have been noted and need attention:

**Content**
There are three UC workflow diagrams missing for the following sections of the BC UC list:

- Query (GET) Transfer - Validation Failure (Invalid Payer Participant)
- Query (GET) Transfer - Validation Failure (Invalid Payee Participant)
- Query (GET) Transfer - Validation Failure (Transfer Identifier Token Not Found)

These are required in order to close out the BC publication process.  I am looking for one or two folks to get involved and assist to complete them.  @mdebarros, if you are available, please let me know.  If not, @pedrosousabarreto, please could you jump in with me and we can get it done.  Thanks.

**Tasks**

- [ ] Create UC workflow diagram using existing Miro board for: Query (GET) Transfer - Validation Failure (Invalid Payer Participant)
- [ ] Create UC workflow diagram using existing Miro board for: Query (GET) Transfer - Validation Failure (Invalid Payee Participant)
- [ ] Create UC workflow diagram using existing Miro board for: Query (GET) Transfer - Validation Failure (Transfer Identifier Token Not Found)

**Acceptance Criteria**

- [ ] TBD

**_Note:** Assignee List to be determined._
